crash:
    - "Crash or freeze"
engraving:
    - "Engraving bug (incorrect score rendering)"
"UX/interaction":
    - "UX/Interaction bug (incorrect behaviour)"
UI:
    - "UI bug (incorrect info or interface appearance)"
VST:
    - "VST bug"
"Muse Sounds":
    - "Muse Sounds bug"
playback:
    - "General playback bug"
cloud:
    - "Cloud issue (opening, saving, logging in/out)"
corruption:
    - "File corruption"
"needs review":
    - "Other type of issue"

regression:
    - "Yes, this used to work in a previous version of MuseScore 4.x"
regression_ms3:
    - "Yes, this used to work in MuseScore 3.x and now is broken"

"feature request":
    - "Problem to be solved"
