name: Bug report
description: File a bug report
body:
  - type: dropdown
    id: label
    attributes:
      label: Issue type
      description: What kind of issue are you experiencing?
      options:
        - Choose option...
        - Crash or freeze
        - Engraving bug (incorrect score rendering)
        - UX/Interaction bug (incorrect behaviour)
        - UI bug (incorrect info or interface appearance)
        - Accessibility issue (e.g. for keyboard-only or screen reader users)
        - VST bug
        - Muse Sounds bug
        - General playback bug
        - Cloud issue (opening, saving, logging in/out)
        - Opening/saving issue
        - Import/export issue
        - File corruption
        - Other type of issue
    validations:
      required: true
  - type: textarea
    id: desc
    attributes:
      label: Bug description
      description: A more detailed description of the bug
      placeholder: Context for the bug that didn't fit in the title
    validations:
      required: false
  - type: textarea
    id: str
    attributes:
      label: Steps to reproduce
      description: Please provide step-by-step instructions to reproduce this bug 
      placeholder: |
        1. go to ...
        2. then click on ...
        3. then ...
    validations:
      required: true
  - type: textarea
    id: evidence
    attributes:
      label: Supporting evidence
      description: |
        * For crashes: crash logs, system information (OS, CPU, GPU, memory, drive type, etc.)
        * For playback issues: Is it using MS Basic, MuseSounds or VSTs?
          * For VSTs in particular: Where did you get the VSTs from? (link)
        * For engraving: sample score (MuseScore project), screenshots
        * For UI issues: Screenshots, screen recordings, system information, GPU drivers
        * For regressions: The last MuseScore version (or even better: commit) that worked well. 
      placeholder: |
        Click into this text box and paste your files or screenshots here.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: MuseScore Version
      description: What version of MuseScore are you running? You can copy the info from the Help > About dialog in MuseScore.
    validations:
      required: true
  - type: dropdown
    id: regression
    attributes:
      label: Regression
      description: Did this work before? Older versions of MuseScore Studio can be found [here](https://github.com/musescore/MuseScore/releases).
      options:
        - Choose option...
        - No.
        - I was unable to check
        - Yes, this used to work in MuseScore 3.x and now is broken 
        - Yes, this used to work in a previous version of MuseScore 4.x
    validations: 
      required: true
  - type: input
    id: os
    attributes:
      label: Operating system
      description: What OS does this bug occur on?
      placeholder: Windows 11, macOS 13, Ubuntu 22.04, etc.
    validations: 
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Further information which may be relevant to this bug

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: "Before submitting your bug report, please make sure the following requirements are met:"
      options:
        - label: "This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues"
          required: true
        - label: "I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues"
          required: true
        - label: "I have attached all requested files and information to this report"
          required: true
        - label: "I have attempted to identify the root problem as concisely as possible, and have used minimum reproducible examples where possible"
          required: true
  - type: markdown
    attributes:
      value: If an issue does not meet these requirements, it may be closed without investigation.
